version: '1.0'

services:
  product_service_mongodb:
    image: mongo
    container_name: product_service_mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
  
  order_service_postgres:
    image: postgres
    container_name: order_service_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
  