version: '3.1'

services:
  mongodb:
    image: mongo
    container_name: book_service_mongodb
    restart: always
    ports:
      - "27017:27017"
    # environment:
      # MONGO_INITDB_DATABASE: admin
      # MONGO_INITDB_ROOT_USERNAME: root
      # MONGO_INITDB_ROOT_PASSWORD: password